### PR TITLE
Fixed alias already known path

### PR DESCRIPTION
**Pull request by eidng8**

### CODE REVIEW

**Comment by marcharding** [comment]
Please resubmit to current develop, it wants to merge with the broken appveyor-process now, thanks...

**Comment by eidng8** [comment]
This branch: https://github.com/marcharding/winnfsd/tree/develop ?

It seems the previous PR is not there yet. So I should submit the whole thing there?

**Comment by marcharding** [comment]
Yes, please :bowtie:

**Comment by marcharding** [comment]
closed by #4

**Pull request closed without merging**
